module.exports = {
  apps: [
    {
      name:         'dark-omens-relay',
      script:       'node_modules/tsx/dist/cli.mjs',
      args:         'src/relay/server.ts',
      cwd:          __dirname,
      watch:        false,
      autorestart:  true,
      max_restarts: 50,
      min_uptime:   '5s',
      restart_delay: 2000,
      env: {
        RELAY_PORT:        '3030',
        NODE_ENV:          'production',
        LOG_LEVEL:         'INFO',
        EMPTY_ROOM_TTL_MS: String(7 * 24 * 60 * 60 * 1000),
        // ADMIN_KEY:      'changeme',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file:    'logs/relay-out.log',
      error_file:  'logs/relay-err.log',
      max_size:    '20M',
      retain:      7,
      compress:    true,
    },
    {
      name:         'dark-omens-api',
      script:       'node_modules/tsx/dist/cli.mjs',
      args:         'src/api/server.ts',
      cwd:          __dirname,
      watch:        false,
      autorestart:  true,
      max_restarts: 50,
      min_uptime:   '5s',
      restart_delay: 2000,
      env: {
        API_PORT:        '3031',
        NODE_ENV:        'production',
        LOG_LEVEL:       'INFO',
        DEV_MODE:        'false',
        RESEND_API_KEY:  're_your_key_here',
        // EMAIL_FROM:   'Dark Omens <noreply@dark-omens.game>',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file:   'logs/api-out.log',
      error_file: 'logs/api-err.log',
      max_size:   '20M',
      retain:     7,
      compress:   true,
    },
  ],
};
